namespace VideoGenerator.AllConstants;

public static partial class Constants
{
    private static readonly List<string> _generalTopics =
        [
            "Health and medicine",
            "Travel and tourism",
            "Education and self - improvement",
            "Technology and science",
            "Arts and culture",
            "Finance and investments",
            "Entertainment and gaming",
            "Fashion and style",
            "Pets and animals",
            "Food and culinary",
            "Psychology and psychotherapy",
            "Sports and fitness",
            "Home improvement and construction",
            "Music and movies",
            "Design and architecture",
            "Software engineering and computer science",
            "Politics",
            "Zdrowie i medycyna",
            "Podróże i turystyka",
            "Edukacja i samodoskonalenie",
            "Technologia i nauka",
            "Sztuka i kultura",
            "Finanse i inwestycje",
            "Rozrywka i gry",
            "Moda i styl",
            "Zwierzęta domowe",
            "Jedzenie i kulinaria",
            "Psychologia i psychoterapia",
            "Sport i fitness",
            "Remont i budownictwo",
            "Muzyka i filmy",
            "Projektowanie i architektura",
            "Informatyka i nauki komputerowe",
            "Polityka",
            "Здоров’я і медицина",
            "Подорожі та туризм",
            "Освіта та самовдосконалення",
            "Технології та наука",
            "Мистецтво і культура",
            "Фінанси та інвестиції",
            "Розваги та гри",
            "Мода і стиль",
            "Домашні тварини",
            "Їжа та кулінарія",
            "Психологія та психотерапія",
            "Спорт і фітнес",
            "Будівництво та ремонт будинку",
            "Музика і фільми",
            "Дизайн і архітектура",
            "Програмування та комп’ютерні науки",
            "Політика",
            "Salud y medicina",
            "Viajes y turismo",
            "Educación y auto - mejora",
            "Tecnología y ciencia",
            "Arte y cultura",
            "Finanzas e inversiones",
            "Entretenimiento y juegos",
            "Moda y estilo",
            "Mascotas y animales",
            "Comida y cocina",
            "Psicología y psicoterapia",
            "Deportes y fitness",
            "Mejoras en el hogar y construcción",
            "Música y películas",
            "Diseño y arquitectura",
            "Ingeniería de software y ciencias de la computación",
            "Política",
            "Gesundheit und Medizin",
            "Reisen und Tourismus",
            "Bildung und Selbstverbesserung",
            "Technologie und Wissenschaft",
            "Kunst und Kultur",
            "Finanzen und Investitionen",
            "Unterhaltung und Spiele",
            "Mode und Stil",
            "Haustiere und Tiere",
            "Essen und Kulinarik",
            "Psychologie und Psychotherapie",
            "Sport und Fitness",
            "Hausverbesserung und Bau",
            "Musik und Filme",
            "Design und Architektur",
            "Softwareentwicklung und Informatik",
            "Politik",
            "Здоровье и медицина",
            "Путешествия и туризм",
            "Образование и самосовершенствование",
            "Технологии и наука",
            "Искусство и культура",
            "Финансы и инвестиции",
            "Развлечения и игры",
            "Мода и стиль",
            "Домашние животные",
            "Еда и кулинария",
            "Психология и психотерапия",
            "Спорт и фитнес",
            "Строительство и ремонт дома",
            "Музыка и фильмы",
            "Дизайн и архитектура",
            "Программирование и компьютерные науки",
            "Политика"
        ];

    public static IReadOnlyCollection<string> GeneralTopics => _generalTopics;
}