// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGenerator.Infrastructure;

#nullable disable

namespace VideoGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240307194635_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("AttachmentPublishedMessage", b =>
                {
                    b.Property<long>("AttachmentsAttachmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedMessagesPublishedMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentsAttachmentId", "PublishedMessagesPublishedMessageId");

                    b.HasIndex("PublishedMessagesPublishedMessageId");

                    b.ToTable("AttachmentPublishedMessage");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Attachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<long>("QueueMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentId")
                        .HasName("PK_AttachmentId");

                    b.HasIndex("QueueMessageId");

                    b.HasIndex("AttachmentId", "QueueMessageId")
                        .IsDescending()
                        .HasDatabaseName("UI_AttachmentId_MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId")
                        .HasName("PK_GroupId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TopicId", "GroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_TopicId_GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Language", b =>
                {
                    b.Property<long>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LanguageId")
                        .HasName("PK_LanguageId");

                    b.HasIndex("TopicId");

                    b.HasIndex("LanguageId", "LanguageCode")
                        .IsDescending()
                        .HasDatabaseName("UI_LanguageId_LanguageCode");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.PublishedMessage", b =>
                {
                    b.Property<long>("PublishedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StolenAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("PublishedMessageId")
                        .HasName("PK_PublishedMessageId");

                    b.HasIndex("SourceGroupId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PublishedMessageId", "TargetGroupId", "SourceGroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_PublishedMessageId_GroupId");

                    b.ToTable("PublishedMessages", t =>
                        {
                            t.HasCheckConstraint("CK_Published_Message_Text", "LENGTH(Text) > 1");
                        });
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.Property<long>("QueueMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StolenAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Text");

                    b.HasKey("QueueMessageId")
                        .HasName("PK_QueueMessageId");

                    b.HasIndex("PublishedMessageId")
                        .IsUnique();

                    b.HasIndex("SourceGroupId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("QueueMessageId", "TargetGroupId", "SourceGroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_QueueMessageId_GroupId");

                    b.ToTable("QueueMessages", t =>
                        {
                            t.HasCheckConstraint("CK_Message_Text", "LENGTH(Text) > 1");
                        });
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Topic", b =>
                {
                    b.Property<long>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicName")
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId")
                        .HasName("PK_TopicId");

                    b.HasIndex("TopicName", "TopicId")
                        .IsDescending()
                        .HasDatabaseName("UI_TopicName_TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("AttachmentPublishedMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentsAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.PublishedMessage", null)
                        .WithMany()
                        .HasForeignKey("PublishedMessagesPublishedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Attachment", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.QueueMessage", "QueueMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("QueueMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueMessage");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Language", "Language")
                        .WithMany("Groups")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Topic", "Topic")
                        .WithMany("Groups")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Language", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Topic", null)
                        .WithMany("AvailableLanguages")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.PublishedMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "SourceGroup")
                        .WithMany("OutputPublishedMessages")
                        .HasForeignKey("SourceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "TargetGroup")
                        .WithMany("InputPublishedMessages")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceGroup");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.PublishedMessage", "PublishedMessage")
                        .WithOne("QueueMessage")
                        .HasForeignKey("VideoGenerator.Infrastructure.Entities.QueueMessage", "PublishedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "SourceGroup")
                        .WithMany("OutputQueueMessages")
                        .HasForeignKey("SourceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "TargetGroup")
                        .WithMany("InputQueueMessages")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PublishedMessage");

                    b.Navigation("SourceGroup");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.Navigation("InputPublishedMessages");

                    b.Navigation("InputQueueMessages");

                    b.Navigation("OutputPublishedMessages");

                    b.Navigation("OutputQueueMessages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Language", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.PublishedMessage", b =>
                {
                    b.Navigation("QueueMessage");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Topic", b =>
                {
                    b.Navigation("AvailableLanguages");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
