// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoGenerator.Infrastructure;

#nullable disable

namespace VideoGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313210937_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttachmentPublishedMessage", b =>
                {
                    b.Property<long>("AttachmentsAttachmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PublishedMessagesPublishedMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("AttachmentsAttachmentId", "PublishedMessagesPublishedMessageId");

                    b.HasIndex("PublishedMessagesPublishedMessageId");

                    b.ToTable("AttachmentPublishedMessage");
                });

            modelBuilder.Entity("LanguageTopic", b =>
                {
                    b.Property<int>("AvailableLanguagesLanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("TopicsTopicId")
                        .HasColumnType("integer");

                    b.HasKey("AvailableLanguagesLanguageId", "TopicsTopicId");

                    b.HasIndex("TopicsTopicId");

                    b.ToTable("LanguageTopic");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Attachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<long>("QueueMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("AttachmentId")
                        .HasName("PK_AttachmentId");

                    b.HasIndex("QueueMessageId");

                    b.HasIndex("AttachmentId", "QueueMessageId")
                        .IsDescending()
                        .HasDatabaseName("UI_AttachmentId_MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupLink")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId")
                        .HasName("PK_GroupId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TopicId", "GroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_TopicId_GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.HasKey("LanguageId")
                        .HasName("PK_LanguageId");

                    b.HasIndex("LanguageId", "LanguageCode")
                        .IsDescending()
                        .HasDatabaseName("UI_LanguageId_LanguageCode");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.PublishedMessage", b =>
                {
                    b.Property<long>("PublishedMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StolenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TargetGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublishedMessageId")
                        .HasName("PK_PublishedMessageId");

                    b.HasIndex("SourceGroupId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("PublishedMessageId", "TargetGroupId", "SourceGroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_PublishedMessageId_GroupId");

                    b.ToTable("PublishedMessages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.Property<long>("QueueMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("PublishedMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StolenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TargetGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QueueMessageId")
                        .HasName("PK_QueueMessageId");

                    b.HasIndex("PublishedMessageId");

                    b.HasIndex("SourceGroupId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("QueueMessageId", "TargetGroupId", "SourceGroupId")
                        .IsDescending()
                        .HasDatabaseName("UI_QueueMessageId_GroupId");

                    b.ToTable("QueueMessages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicId"));

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("TopicName")
                        .HasColumnType("text");

                    b.HasKey("TopicId")
                        .HasName("PK_TopicId");

                    b.HasIndex("TopicName", "TopicId")
                        .IsDescending()
                        .HasDatabaseName("UI_TopicName_TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("AttachmentPublishedMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentsAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.PublishedMessage", null)
                        .WithMany()
                        .HasForeignKey("PublishedMessagesPublishedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageTopic", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("AvailableLanguagesLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Attachment", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.QueueMessage", "QueueMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("QueueMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueMessage");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Language", "Language")
                        .WithMany("Groups")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Topic", "Topic")
                        .WithMany("Groups")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.PublishedMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "SourceGroup")
                        .WithMany("OutputPublishedMessages")
                        .HasForeignKey("SourceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "TargetGroup")
                        .WithMany("InputPublishedMessages")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceGroup");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.HasOne("VideoGenerator.Infrastructure.Entities.PublishedMessage", "PublishedMessage")
                        .WithMany()
                        .HasForeignKey("PublishedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "SourceGroup")
                        .WithMany("OutputQueueMessages")
                        .HasForeignKey("SourceGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Infrastructure.Entities.Group", "TargetGroup")
                        .WithMany("InputQueueMessages")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PublishedMessage");

                    b.Navigation("SourceGroup");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Group", b =>
                {
                    b.Navigation("InputPublishedMessages");

                    b.Navigation("InputQueueMessages");

                    b.Navigation("OutputPublishedMessages");

                    b.Navigation("OutputQueueMessages");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Language", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.QueueMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("VideoGenerator.Infrastructure.Entities.Topic", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
