// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoGenerator.Infrastructure;

#nullable disable

namespace VideoGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016151319_AddTimestampsForTtsSubtitles")]
    partial class AddTimestampsForTtsSubtitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedSubtitle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssBlobPath")
                        .HasColumnType("text");

                    b.Property<string>("Timestamps")
                        .HasColumnType("text");

                    b.Property<string>("TtsBlobPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneratedSubtitle", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenerationQueueId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenerationQueueId");

                    b.ToTable("GeneratedVideos", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GenerationQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("GenerationQueue", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.SplitHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("LastTookPartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentBlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SplitHistories", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedVideo", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GenerationQueueItem", "GenerationQueueItem")
                        .WithMany()
                        .HasForeignKey("GenerationQueueId");

                    b.Navigation("GenerationQueueItem");
                });
#pragma warning restore 612, 618
        }
    }
}
