// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoGenerator.Infrastructure;

#nullable disable

namespace VideoGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130144657_PublishBatch")]
    partial class PublishBatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedSubtitle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssBlobPath")
                        .HasColumnType("text");

                    b.Property<string>("Timestamps")
                        .HasColumnType("text");

                    b.Property<string>("TtsBlobPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneratedSubtitle", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GenerationQueueId")
                        .HasColumnType("text");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TotalParts")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UploadingStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenerationQueueId");

                    b.ToTable("GeneratedVideos", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GenerationQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SexType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("YoutubePlaylistId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenerationQueue", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.InterestingFactQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("YoutubePlaylistId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InterestingFactQueueItem");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastPublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PublishAccounts", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationQueueItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GenerationQueueItemId");

                    b.ToTable("PublishBatches", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaylistId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PublishAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PublishBatchId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PublishAccountId");

                    b.HasIndex("PublishBatchId", "PublishAccountId")
                        .IsUnique();

                    b.ToTable("PublishQueueItems", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.ScheduledUpload", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeneratedVideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PublishQueueItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedVideoId");

                    b.HasIndex("PublishQueueItemId", "GeneratedVideoId")
                        .IsUnique();

                    b.HasIndex("ScheduledAt", "Status");

                    b.ToTable("ScheduledUploads", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.SplitHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("LastTookPartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentBlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SplitHistories", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.VideoUploadHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeneratedVideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("UploadType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedVideoId", "UploadType")
                        .IsUnique();

                    b.ToTable("VideoUploadHistories", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedVideo", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GenerationQueueItem", "GenerationQueueItem")
                        .WithMany()
                        .HasForeignKey("GenerationQueueId");

                    b.Navigation("GenerationQueueItem");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishBatch", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GenerationQueueItem", "GenerationQueueItem")
                        .WithMany()
                        .HasForeignKey("GenerationQueueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationQueueItem");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishQueueItem", b =>
                {
                    b.HasOne("VideoGenerator.Entities.PublishAccount", "PublishAccount")
                        .WithMany("PublishQueueItems")
                        .HasForeignKey("PublishAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Entities.PublishBatch", "PublishBatch")
                        .WithMany("PublishQueueItems")
                        .HasForeignKey("PublishBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishAccount");

                    b.Navigation("PublishBatch");
                });

            modelBuilder.Entity("VideoGenerator.Entities.ScheduledUpload", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GeneratedVideo", "GeneratedVideo")
                        .WithMany()
                        .HasForeignKey("GeneratedVideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGenerator.Entities.PublishQueueItem", "PublishQueueItem")
                        .WithMany("ScheduledUploads")
                        .HasForeignKey("PublishQueueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedVideo");

                    b.Navigation("PublishQueueItem");
                });

            modelBuilder.Entity("VideoGenerator.Entities.VideoUploadHistory", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GeneratedVideo", "GeneratedVideo")
                        .WithMany()
                        .HasForeignKey("GeneratedVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedVideo");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishAccount", b =>
                {
                    b.Navigation("PublishQueueItems");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishBatch", b =>
                {
                    b.Navigation("PublishQueueItems");
                });

            modelBuilder.Entity("VideoGenerator.Entities.PublishQueueItem", b =>
                {
                    b.Navigation("ScheduledUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
