// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoGenerator.Infrastructure;

#nullable disable

namespace VideoGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809200611_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClearMetadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedSubtitleId")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("GenerationDuration")
                        .HasColumnType("interval");

                    b.Property<string>("RawMetadata")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneratedHistories", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedSubtitle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedHistoryId")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("GenerationDuration")
                        .HasColumnType("interval");

                    b.Property<string>("ProcessedVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedHistoryId")
                        .IsUnique();

                    b.ToTable("GeneratedSubtitle", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.ProcessedVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("GeneratedSubtitleId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ProcessingDuration")
                        .HasColumnType("interval");

                    b.Property<string>("SourceVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedSubtitleId")
                        .IsUnique();

                    b.HasIndex("SourceVideoId");

                    b.ToTable("ProcessedVideos", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.SourceVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SourceVideos", (string)null);
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedSubtitle", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GeneratedHistory", "GeneratedHistory")
                        .WithOne("GeneratedSubtitle")
                        .HasForeignKey("VideoGenerator.Entities.GeneratedSubtitle", "GeneratedHistoryId");

                    b.Navigation("GeneratedHistory");
                });

            modelBuilder.Entity("VideoGenerator.Entities.ProcessedVideo", b =>
                {
                    b.HasOne("VideoGenerator.Entities.GeneratedSubtitle", "GeneratedSubtitle")
                        .WithOne("ProcessedVideo")
                        .HasForeignKey("VideoGenerator.Entities.ProcessedVideo", "GeneratedSubtitleId");

                    b.HasOne("VideoGenerator.Entities.SourceVideo", "SourceVideo")
                        .WithMany("ProcessedVideos")
                        .HasForeignKey("SourceVideoId");

                    b.Navigation("GeneratedSubtitle");

                    b.Navigation("SourceVideo");
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedHistory", b =>
                {
                    b.Navigation("GeneratedSubtitle");
                });

            modelBuilder.Entity("VideoGenerator.Entities.GeneratedSubtitle", b =>
                {
                    b.Navigation("ProcessedVideo");
                });

            modelBuilder.Entity("VideoGenerator.Entities.SourceVideo", b =>
                {
                    b.Navigation("ProcessedVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
